### ISSUE TITLE
Failed to reproduce brunnermunzel.permutation.test fully.

### ISSUE THREAD

**Issue by karchjd** [toshi-ara/brunnermunzel#14]
To make sure that I understand the brunnermunzel test fully, I implemented the permutation version myself. To test my results, I compared it with your package. 

Overall, our results almost agree. My function to compute the test-statistic returns the same output as your package and the obtained p-values agree in 80/100 tests I did. However, in 20 cases the p-values do not agree.

Naturally, my suspicion was that my permutation function is wrong. However, if I used wilcxons W as test statistic for my function, it always returns exactly the same p-value as the wilcox.test function from the base package.

My suspicion is that something strange is going on in the 20% of the cases our functions do not agree.  I thought you might be interested in knowing that. I attached an R script demonstrating what I summarized. I would be delighted if you found the time to look into this.
[mwe.R.zip](https://github.com/toshi-ara/brunnermunzel/files/4395032/mwe.R.zip)

**Comment by trevismd** [comment]
Hello,

I am also interested in this issue as I wanted to use the package but must now be cautious. Has anyone found anything yet ?

Thanks

**Comment by trevismd** [comment]
@karchjd 's code is probably more strict about equality than other implementations (and than it probably should because of floating point precision past a certain number of decimal places)

Please consider this permutation:

```r
x1 <- c(-0.75,  0.18, -2.33,  1.27, -1.2)
y1 <- c(-0.05, -0.41, -1.3,   1.1,  -0. )

x2 <- c(-0.05, -0.41, -0.75, -1.3,   1.1)
y2 <- c( 0.18, -0.,   -2.33,  1.27, -1.2 )

a1 <- BrunnerMunzelStat(x1, y1)
a2 <- BrunnerMunzelStat(x2, y2)
a1
# [1] 0.2761724

a2
# [1] 0.2761724  # OK so far

a1 == a2
# [1] FALSE

a1 - a2
# [1] -1.110223e-16 

library(dplyr)
near(a1, a2)
# [1] TRUE  # And so this function exists :)
```
While
```R
b1 <- brunnermunzel.test(x1, y1)$statistic
b2 <- brunnermunzel.test(x2, y2)$statistic
b1
# Brunner-Munzel Test Statistic
#                    0.2761724

b2
# Brunner-Munzel Test Statistic
#                     0.2761724

b1 == b2

# Brunner-Munzel Test Statistic
#                          TRUE
```

If we compute the permutation tests on `x1, y1`, you find equal `W` in 5 cases while I find 12 (reimplemented in Python). 

Out of 252 combinations, this explains the 0.8253968.. (this package and I) to 0.7698412.. pvalue (`(12 - 5) * 2 / 252 = 0.555...5`).

Your code could be modified to 
- first count those near values
- then the larger and smaller values that are not already counted as near values
- add the near values count to both the larger and the smaller counts.

That said, I still have a few differences with this package too, so I'll keep digging a bit.

**Comment by trevismd** [comment]
16 of the 20 differences were due to this (above) (with explicit handling of Inf values after `near`)
For the last 4 of them (\#22, 34, 71 and 78 of 100), I checked that all BM statistic values of permutations are also equal between implementations.

However, there is a difference of 1 in the counts for the two-sided and in one of the one-sided hypotheses.
For the first two cases, where the initial statistic is negative, there is an error in the `two-sided` and `greater `alternatives.
In the last two, where the initial statistic is positive, there is an error in the `two-sided` and `less`alternatives.

I know nothing of FORTRAN, so I'll just try and guess something. Is it possible that arithmetic or logical operations on infinite values aren't robust ? I didn't find something handling these cases in the code, but it might not be necessary, I don't know.

**Comment by toshi-ara** [comment]
@karchjd @trevismd 
I’m sorry for the late reply.
I corrected this issue and submited to CRAN.

### serious change
* return TRUE in X >= Y when X is near to Y in FORTRAN program
    * Thanks to Gen Kuroki (@genkuroki)
    * refer to this tweet (https://twitter.com/genkuroki/status/1555694373631033344) (in Japanese)

**Comment by karchjd** [comment]
There still seems to be a conflict between version 2.0 and my R implementation. Are we sure that the version 2.0 implementation is what we want? I have to admit that I could not completely follow the findings of @trevismd  as well as the tweet of @genkuroki.

**Comment by trevismd** [comment]
Hello @karchjd , 

Could you post the updated results of you comparison please? 
I mean the test cases, your results (possibly after updated as described below if it makes sense), and the ones from this new version ? 
(I do not have R installed at the moment). I'll run my python implementation on these and compare though (https://github.com/trevismd/permutations-stats).

About this,
> I could not completely follow the findings of @trevismd

What I meant in my first message is that sometimes you get two values that should be identical and considered identical because they are mathematically, but are not for the computer because of how floating point numbers are represented (with a certain degree of precision, see https://academind.com/tutorials/floating-point-precision-and-arithmetic for an intro/summary).

You can see that in the first case, values are only different by about 1e16, they are actually identical, like 1.000000000000000000001 is 1 for most intent and purposes; but your implementation would consider one to be greater than the other, hence the inaccurate results (in 16 cases at least at the time). 

You could use `near` from `dplyr` to correct for this.

**Comment by karchjd** [comment]
@trevismd

Thanks for the additional explanation. I understand it better now. I would not have expected floating point problems both because we use `>=` and not `==`, and because the computations seem rather simple. Would be curious to know why we do not get those for the Wilcoxon test. I guess because we do not divide by the variance estimate? 

I changed my code according to your suggestions. Specifically, I exchanged lines 74-75 with

```
pValSmaller <- sum(W <= hypothetical | near(W,hypothetical))/permutations
pValGreater <- sum(W >= hypothetical | near(W,hypothetical))/permutations
```
and now get exactly the same p values as `brunnermunzel` version 2.0, and exactly the same conflicts you have mentioned (#22, 34, 71 and 78 of 100), when using earlier versions.

**Comment by trevismd** [comment]
@karchjd , thanks for the quick feedback!

I guess that both your implementations indeed suffured from this and are now fixed :-)

Too bad I wasn't clear enough to help induce changes two years ago 😉 @toshi-ara .

(@karchjd If there are no duplicate values, the Wilcoxon statistics for independent samples is always an integer, which doesn't suffer from this precision limitation.)
